# 开发环境配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/af_user?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: password

server:
  port: 8080
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis-mappers/*.xml
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1